### ISSUE TITLE
Gradle platform support

### ISSUE THREAD

**Issue by 0ffz** [SlimJar/slimjar#20]
Gradle lets you create [platform projects](https://docs.gradle.org/current/userguide/platforms.html#sub:using-platform-to-control-transitive-deps) that only contain dependencies or dependency constraints.

Currently, I think slimjar attempts to get the jar for the project itself which fails due to the platform not actually having any jar published. I don't know how it works under the hood but I think they're basically just some transitive dependencies.

I would like to be able to define a `slim(platform("group:name:version"))` in Gradle and have all the dependencies from that platform be downloaded.

Thanks for your time!

**Comment by Vshnv** [comment]
Gradle platform support has been added in release 1.2.1

Kindly reopen the issue if you have further suggestions on this.
Thank you.
