### ISSUE TITLE
Depending on a project that uses slimjar requires adding a repository

### ISSUE THREAD

**Issue by 0ffz** [slimjar/slimjar#21]
Say project `A` uses slimjar, and `B` is a project that depends on `A`.

`compileOnly(A)` works fine, but

`implementation(A)` will result in an error (ex. `Could not resolve io.github.slimjar:slimjar:1.2.0`).

To fix this `B` must add `https://repo.vshnv.tech/` to its list of repositories, which is a little annoying. Is this intended?

**Comment by Vshnv** [comment]
This is indeed unintended behavior. We will get to resolving this asap.

Thank you for the report.

**Comment by Vshnv** [comment]
This seems to be the default behavior of gradle even on normal multi-module projects. Altho @ipsk has mentioned some changes earlier that would resolve this issue.
