### ISSUE TITLE
Problem when downloading a dependency

### ISSUE THREAD

**Issue by Lorenzo0111** [SlimJar/slimjar#22]
I don't know if it is a slimjar problem.
When I try to load the jar it gives an error.

**Files:**
- [Error](https://paste.helpch.at/iwuwirijan.pl)
- [build.gradle](https://paste.helpch.at/ovedawihaw.php)
- [slimjar.json inside the jar](https://paste.helpch.at/afasepabaf.json)

**Comment by Vshnv** [comment]
Yes, this is currently being looked into. Its occurs due to transitive platform dependencies. A patch will be released shortly. 

Thank you for your report.

**Comment by Lorenzo0111** [comment]
Ok, thanks

**Comment by Vshnv** [comment]
Fixed in release 1.2.1

Kindly reopen the issue if you find further issues.

**Comment by Lorenzo0111** [comment]
I have the same error.
https://paste.helpch.at/inogaxapil.pl

**Comment by Vshnv** [comment]
Please make sure that you are on 1.2.1.
