### ISSUE TITLE
Could not determine the dependencies of task ':publishMavenJavaPublicationToMavenRepository'.

### ISSUE THREAD

**Issue by Lorenzo0111** [SlimJar/slimjar#24]
I'm quite sure that it is a slimjar problem.

When I try to run the task `gradlew clean build publish` it gives me the error in the title.
You can view a build log [here](https://ci.codemc.io/job/Lorenzo0111/job/MultiLang/8/consoleText).

build.gradle: https://github.com/Lorenzo0111/MultiLang/blob/82fe6c6f77be4cdc135d8e41d09d6e7ab15fadad/build.gradle

**Comment by Vshnv** [comment]
Hi,
Your build log seems to suggest this is not caused by slimjar.

**Comment by Vshnv** [comment]
From what could infer, your issue seems to be due to the last line in your build file. You have a recursive dependency, you have added shadowJar as a dependency of the build task.

**Comment by Lorenzo0111** [comment]
I've treid to remove it but I get the same error.

**Comment by Vshnv** [comment]
Please post your updated build file.

**Comment by Lorenzo0111** [comment]
**Gradle Scan:** https://scans.gradle.com/s/cx2ificudhbeq
**Console Log:** https://scans.gradle.com/s/cx2ificudhbeq/console-log/raw
**build.gradle:** https://hastebin.com/pikamixocu.php

**Comment by Vshnv** [comment]
Is `description` a local system/gradle property? 
On line 101, you are setting your publication's artifactId to that, the build logs seems to specify a missing value to artifactId.

**Comment by Lorenzo0111** [comment]
Ok, I've fixed it and now it works, thanks.
