### ISSUE TITLE
Library requiring loading into PluginClassLoader

### ISSUE THREAD

**Issue by Lorenzo0111** [SlimJar/slimjar#25]
On spigot 1.17 it gives this error with all libraries:
```bash
IllegalArgumentException: class <class> is not provided by class org.bukkit.plugin.java.PluginClassLoader
```
is it a bug? is there a way to fix?

**Comment by Vshnv** [comment]
Could you send the complete stack-trace and the `slimjar.json` file inside your jar?

**Comment by Lorenzo0111** [comment]
**Error:** https://hastebin.com/filunafuho.properties
**slimjar.json:** https://hastebin.com/iyejunukul.json

**Comment by Vshnv** [comment]
This seems to not be an issue with dependency injection but rather from the library that was injected using JavaPlugin#getPlugin. That only works on classes loaded by bukkit/spigot.

**Comment by Vshnv** [comment]
Fix has been merged. Please wait for release 1.2.3.
