### ISSUE TITLE
[Question/Suggestion] Redundant relocated jars

### ISSUE THREAD

**Issue by 0ffz** [slimjar/slimjar#37]
I've noticed slimjar generates a copy of every dependency for every application using it under a `relocated` folder regardless of whether anything was relocated. I'm curious as to whether there's a reason for this, seeing as the files aren't exactly identical in size. If not, is there currently a way to avoid this behaviour?

**Comment by Vshnv** [comment]
The reason for this was for different applications to be able to share the same downloaded dependency and each have different relocated jars. 

Another advantage is to property be able to detect change in the library version with the hash from the repo.

If needed, you can customize the behavior of each component by providing different implementations in the ApplicationBuilder. 
Heres what I would recommend for your requirement:
1. Make an implementation of [RelocationHelper](https://github.com/slimjar/slimjar/blob/master/slimjar/src/main/java/io/github/slimjar/relocation/helper/RelocationHelper.java) that does not generate anything. Use this as the relocationHelper in the application builder.

2. Make a DependencyDownloader implementation that uses the default impl  [URLDependencyDownloader](https://github.com/slimjar/slimjar/blob/master/slimjar/src/main/java/io/github/slimjar/downloader/URLDependencyDownloader.java) and relocates it there itself using [JarFileRelocator](https://github.com/slimjar/slimjar/blob/master/slimjar/src/main/java/io/github/slimjar/relocation/JarFileRelocator.java).
