### ISSUE TITLE
Choose download location for SlimJar's own dependencies

### ISSUE THREAD

**Issue by Kopo942** [slimjar/slimjar#41]
Already talked about this in #36, but decided to make a new issue for tracking purposes. It would be great if I could choose the location where SlimJar drops its own dependencies, out of the `$HOME` directory. We're waiting to implement SlimJar into our plugin, but currently this feature being missing is blocking our implementation.

**Comment by Vshnv** [comment]
This is currently already available in version 1.2.4. It downloads its own dependencies in the provided path as well now.
To use 1.2.4, please create a `gradle.properties` file in your project root and add `slimjar.version = 1.2.4` to it.

**Comment by Kopo942** [comment]
Oh, great! This wasn't immediately obvious from the commits / patch notes, so didn't realize it was already implemented. Thanks a lot! :)
