### ISSUE TITLE
Multi-module issue.

### ISSUE THREAD

**Issue by portlek** [slimjar/slimjar#45]
I have A and B modules.
A is like a common module.
B depends A.

I'm using `slim 'xx:yy:zz'` on A module but dependencies don't come to B module so, I have to write all dependencies which are in the A module to B module's dependencies again.

I think we should able to use the A module's dependencies in the B module without the duplication.

Real example:
![image](https://user-images.githubusercontent.com/12835420/126555834-dc158c0d-0d3a-4823-b8d7-3d5a852548be.png)
![image](https://user-images.githubusercontent.com/12835420/126555846-216d6dfa-75a7-41f9-b8f3-ea1e4097374e.png)

**Comment by Vshnv** [comment]
Use the `java-library` plugin in your common project, then you will have access to the slimApi configuration which will expose the dependencies to the dependent.

**Comment by portlek** [comment]
@Vshnv where should i use this `slimApi`? In the common module's dependencies?
like that
![image](https://user-images.githubusercontent.com/12835420/126699866-0c0ffc35-04f2-40ee-ae25-d04a1b579da9.png)

**Comment by portlek** [comment]
I did like tha image, it's quite working but don't writing dependencies into the .json file.

**Comment by Vshnv** [comment]
I see, Ill look into checking for transitive dependencies with that config

**Comment by portlek** [comment]
any progress?

**Comment by Vshnv** [comment]
This isnt currently a priority, working on a few other issues rn. This issue is currently open for anyone to try to fix
