### ISSUE TITLE
Can't inject dependencies

### ISSUE THREAD

**Issue by Lorenzo0111** [slimjar/slimjar#48]
The injector works for most users but there is an user who reported the injector is not working with him.
I tried lots of things but nothing..

[Full log here.](https://hastebin.com/hecixoxizi.properties)

If you need some other file just ask. Thanks in advance

**Comment by Vshnv** [comment]
That looks like an exception from an older version, kindly use 1.2.4 or the snapshot release of 1.2.5

**Comment by Lorenzo0111** [comment]
> 
> 
> That looks like an exception from an older version, kindly use 1.2.4 or the snapshot release of 1.2.5

How can I update it? I'm using the gradle plugin

**Comment by Vshnv** [comment]
Try creating a "gradle.properties" file in your project root and adding `slimjar.version = 1.2.4` to it

**Comment by Lorenzo0111** [comment]
> Try creating a "gradle.properties" file in your project root and adding `slimjar.version = 1.2.4` to it

Already tried: https://github.com/Lorenzo0111/ElectionsPlus/blob/master/gradle.properties

**Comment by Vshnv** [comment]
Alrighty, kindly ask the user their exact java version. The one you can fetch from `java -version`

**Comment by Lorenzo0111** [comment]
Java 16

**Comment by Vshnv** [comment]
Looking through your project, It seems another library you use called "pluginslib" that depends on slimjar is overriding your version declaration and is using 1.2.1, hence you're getting the issue from the older versions. Kindly request the library author to fix their implementation.

**Comment by Lorenzo0111** [comment]
> Looking through your project, It seems another library you use called "pluginslib" that depends on slimjar is overriding your version declaration and is using 1.2.1, hence you're getting the issue from the older versions. Kindly request the library author to fix their implementation.

Ok

**Comment by Vshnv** [comment]
Could you confirm if this fixed it?

**Comment by Lorenzo0111** [comment]
I'm doing last tests but it seems to work. Thanks

**Comment by Vshnv** [comment]
Thank you
