### ISSUE TITLE
Project fails to build with Gradle plugin v1.2.2

### ISSUE THREAD

**Issue by Kopo942** [slimjar/slimjar#53]
For some reason, `package io.github.slimjar.app.builder does not exist` when using Slimjar Gradle plugin version 1.2.2. With 1.2.1 it builds fine. 

See gradle log here: https://github.com/plan-player-analytics/Plan/runs/3269302665

**Comment by Vshnv** [comment]
Yea, there needs to be a slight documentation update along with the gradle plugin update. Ill get it up tomorrow, was travelling.

**Comment by AuroraLS3** [comment]
Solved by

Add repository
```groovy
repositories {
        maven { url = " https://repo.vshnv.tech/"} // slimjar
}
```
and dependency
```groovy
dependencies {
    implementation slimjar("1.2.5")
}
```
